### ISSUE TITLE
Putting multiple words separated by spaces into the search field does not lead the user to the error page

### ISSUE THREAD

**Issue by RegenKordel** [OpenReqEU/issuelinkmap-jira-plugin#41]
SELECT * FROM REQUIREMENT or Fsafdf afadfds go to an empty issue page 
![image](https://user-images.githubusercontent.com/22965170/68749124-02800d80-05fe-11ea-9927-67ce642930cb.png)

**Comment by MatsSchrader** [comment]
fixed, all invalid inputs should now lead to the error page
