### ISSUE TITLE
Issue Node is very big first time opening the link map

### ISSUE THREAD

**Issue by RegenKordel** [OpenReqEU/issuelinkmap-jira-plugin#59]
If you open the link map with an issue without any depth, it fills out the whole map. (f.e. QTBUG-76315), at least on Chrome.

**Comment by MatsSchrader** [comment]
only happens on nodes without connections
should be fixed with a timeout and a network.fit()

**Comment by MatsSchrader** [comment]
the issue nodes are no longer too big on first load
